export const lightTheme = {
    mode: "light",

    BACKGROUND_SHADOW_BOX: 'initial',
    BACKGROUND_COLOR_SECTION: "#FFFFFF",
    BACKGROUND_COLOR_SECTION_DARKER: "#EAF0F9",
    BACKGROUND_COLOR_FOOTER_SECTION: "#10367C",
    BACKGROUND_COLOR_INPUT: "#FFFFFF",
    BACKGROUND_COLOR_FORM_WRAPPER: "#FFFFFF",
    BACKGROUND_COLOR_SCROLL: "#3077C6",
    BACKGROUND_HOVER_COLOR_SELECT: "#F3F3F4",

    BACKGROUND_COLOR_MODAL: "#FFFFFF",

    COLOR_BORDER_SELECT: "#3077C6",
    COLOR_TEXT_HOVER_SELECT: "#383838",
    COLOR_BORDER_FOCUS_INPUT: "#F5BD41",


    COLOR_NAV_TEXT: "#FFFFFF",
    COLOR_NAV_ICON_ACTIVE_AND_FOCUS: "#F5BD41",
    COLOR_NAV_LOGOTYPE_MAIN: "#3077C6",
    COLOR_NAV_LOGOTYPE: "#FFFFFF",
    COLOR_MODAL_TEXT: "#333333",

    COLOR_NAV_ICON: "#FFFFFF",
    COLOR_OFFER_ICON: "#3077C6",
    COLOR_PROMOTION_ICON: "#3077C6",
    COLOR_AVATAR_ICON: "#BFBFBF",
    COLOR_LOGOUT_ICON: "#333333",
    COLOR_ICON_ACTIVE: "#F5BD41",

    COLOR_MAIN_TITLE: "#FFFFFF",

    COLOR_INPUT_FORM_TEXT: "#383838",
    COLOR_SECTION_TITLE: "#383838",
    COLOR_TITLE: "#383838",
    COLOR_TITLE_CARDS: "#3077C6",
    COLOR_SUB_TITLE: "#BFBFBF",
    COLOR_SUB_TITLE_CARDS: "#3077C6",
    COLOR_PRICE_TEXT:'#FFFFFF',
    COLOR_HOVER_AND_FOCUS: "#F5BD41",
    COLOR_ANY_TEXT: "#383838",
    COLOR_TEXT_REVIEWS: "#BFBFBF",
    COLOR_FOOTER_LINK_:'#FFFFFF',
    COLOR_FOOTER_COPYRIGHT_:'#FFFFFF',

    BTN_SEARCH_BACKGROUND_COLOR: "#3077C6",
    BTN_SEARCH_TEXT_COLOR: "#FFFFFF",
    BTN_SEARCH_BACKGROUND_HOVER_COLOR: "#3057C6",
    BTN_SEARCH_TEXT_HOVER_COLOR: "#F5BD41",

    BTN_LOGOUT_BACKGROUND_COLOR: "#FFFFFF",
    BTN_LOGOUT_TEXT_COLOR: "#333333",
    BTN_LOGOUT_BACKGROUND_HOVER_COLOR: "#3077C6",
    BTN_LOGOUT_TEXT_HOVER_COLOR: "#F5BD41",

    BTN_COUNTER_BACKGROUND_COLOR:'#FFFFFF',
    BTN_COUNTER_ACTIVE_TEXT_COLOR:'#3077C6',
    BTN_COUNTER_ACTIVE_BORDER_COLOR:"#3077C6",
    BTN_COUNTER_IS_NOT_ACTIVE_TEXT_COLOR:"#CECECE",
    BTN_COUNTER_IS_NOT_ACTIVE_BORDER_COLOR:"#CECECE",
    BTN_COUNTER_ACTIVE_HOVER_TEXT_COLOR:'#F5BD41',
    BTN_COUNTER_ACTIVE_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_COUNTER_ACTIVE_HOVER_BORDER_COLOR:'#3077C6',

    BTN_DESTINATIONS_ACTIVE_BACKGROUND_COLOR:'#3077C6',
    BTN_DESTINATIONS_ACTIVE_TEXT_COLOR:'#FFFFFF',
    BTN_DESTINATIONS_IS_NOT_ACTIVE_BACKGROUND_COLOR:"#F3F3F4",
    BTN_DESTINATIONS_IS_NOT_ACTIVE_TEXT_COLOR:"#383838",
    BTN_DESTINATIONS_ACTIVE_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_DESTINATIONS_ACTIVE_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_BOOK_NOW_BACKGROUND_COLOR:'#FFFFFF',
    BTN_BOOK_NOW_BORDER_COLOR:"#3077C6",
    BTN_BOOK_NOW_TEXT_COLOR:'#3077C6',
    BTN_BOOK_NOW_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_BOOK_NOW_HOVER_BORDER_COLOR:"#F5BD41",
    BTN_BOOK_NOW_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_CLOSE_BORDER_COLOR:"#CECECE",
    BTN_CLOSE_TEXT_COLOR:'#FFFFFF',
    BTN_CLOSE_HOVER_BORDER_COLOR:"#CECECE",
    BTN_CLOSE_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_RATING_BACKGROUND_COLOR: "#10367C",
    BTN_RATING_BACKGROUND_HOVER_COLOR: "#10467C",
    BTN_RATING_TEXT_COLOR:"#FFFFFF",


    BTN_TOP_BACKGROUND_COLOR:'#3077C6',
    BTN_TOP_BORDER_COLOR:"#3077C6",
    BTN_TOP_TEXT_COLOR:'#FFFFFF',
    BTN_TOP_HOVER_BACKGROUND_COLOR:'#FFFFFF',
    BTN_TOP_HOVER_BORDER_COLOR:"#3077C6",
    BTN_TOP_HOVER_TEXT_COLOR:'#3077C6',
}

export const darkTheme = {
    mode: "dark",
    BACKGROUND_SHADOW_BOX: 'rgba(18, 18, 18, 0.25)',
    BACKGROUND_COLOR_SECTION: "#4D4D4D",
    BACKGROUND_COLOR_SECTION_DARKER: "#26252D",
    BACKGROUND_COLOR_FOOTER_SECTION: "#10367C",
    BACKGROUND_COLOR_INPUT: "#FFFFFF",
    BACKGROUND_COLOR_FORM_WRAPPER: "#FFFFFF",
    BACKGROUND_COLOR_SCROLL: "#3077C6",
    BACKGROUND_HOVER_COLOR_SELECT: "#F3F3F4",

    BACKGROUND_COLOR_MODAL: "#FFFFFF",

    COLOR_BORDER_SELECT: "#3077C6",
    COLOR_TEXT_HOVER_SELECT: "#383838",
    COLOR_BORDER_FOCUS_INPUT: "#F5BD41",


    COLOR_NAV_TEXT: "#EDEDED",
    COLOR_NAV_ICON_ACTIVE_AND_FOCUS: "#F5BD41",
    COLOR_NAV_LOGOTYPE_MAIN: "#3077C6",
    COLOR_NAV_LOGOTYPE: "#FFFFFF",
    COLOR_MODAL_TEXT: "#333333",

    COLOR_NAV_ICON: "#FFFFFF",
    COLOR_OFFER_ICON: "#EDEDED",
    COLOR_PROMOTION_ICON: "#3077C6",
    COLOR_AVATAR_ICON: "#BFBFBF",
    COLOR_LOGOUT_ICON: "#333333",
    COLOR_ICON_ACTIVE: "#F5BD41",

    COLOR_MAIN_TITLE: "#FFFFFF",

    COLOR_INPUT_FORM_TEXT: "#383838",
    COLOR_SECTION_TITLE: "#EDEDED",
    COLOR_TITLE: "#EDEDED",
    COLOR_TITLE_CARDS: "#A3C6EE",
    COLOR_SUB_TITLE: "#BFBFBF",
    COLOR_SUB_TITLE_CARDS: "#A3C6EE",
    COLOR_PRICE_TEXT:'#FFFFFF',
    COLOR_HOVER_AND_FOCUS: "#F5BD41",
    COLOR_ANY_TEXT: "#383838",
    COLOR_TEXT_REVIEWS: "#BFBFBF",
    COLOR_FOOTER_LINK_:'#EDEDED',
    COLOR_FOOTER_COPYRIGHT_:'#EDEDED',

    BTN_SEARCH_BACKGROUND_COLOR: "#3077C6",
    BTN_SEARCH_TEXT_COLOR: "#FFFFFF",
    BTN_SEARCH_BACKGROUND_HOVER_COLOR: "#3057C6",
    BTN_SEARCH_TEXT_HOVER_COLOR: "#F5BD41",

    BTN_LOGOUT_BACKGROUND_COLOR: "#FFFFFF",
    BTN_LOGOUT_TEXT_COLOR: "#333333",
    BTN_LOGOUT_BACKGROUND_HOVER_COLOR: "#3077C6",
    BTN_LOGOUT_TEXT_HOVER_COLOR: "#F5BD41",

    BTN_COUNTER_BACKGROUND_COLOR:'#FFFFFF',
    BTN_COUNTER_ACTIVE_TEXT_COLOR:'#3077C6',
    BTN_COUNTER_ACTIVE_BORDER_COLOR:"#3077C6",
    BTN_COUNTER_IS_NOT_ACTIVE_TEXT_COLOR:"#CECECE",
    BTN_COUNTER_IS_NOT_ACTIVE_BORDER_COLOR:"#CECECE",
    BTN_COUNTER_ACTIVE_HOVER_TEXT_COLOR:'#F5BD41',
    BTN_COUNTER_ACTIVE_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_COUNTER_ACTIVE_HOVER_BORDER_COLOR:'#3077C6',

    BTN_DESTINATIONS_ACTIVE_BACKGROUND_COLOR:'#3077C6',
    BTN_DESTINATIONS_ACTIVE_TEXT_COLOR:'#FFFFFF',
    BTN_DESTINATIONS_IS_NOT_ACTIVE_BACKGROUND_COLOR:"#F3F3F4",
    BTN_DESTINATIONS_IS_NOT_ACTIVE_TEXT_COLOR:"#383838",
    BTN_DESTINATIONS_ACTIVE_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_DESTINATIONS_ACTIVE_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_BOOK_NOW_BACKGROUND_COLOR:'#FFFFFF',
    BTN_BOOK_NOW_BORDER_COLOR:"#3077C6",
    BTN_BOOK_NOW_TEXT_COLOR:'#3077C6',
    BTN_BOOK_NOW_HOVER_BACKGROUND_COLOR:'#3077C6',
    BTN_BOOK_NOW_HOVER_BORDER_COLOR:"#F5BD41",
    BTN_BOOK_NOW_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_CLOSE_BORDER_COLOR:"#CECECE",
    BTN_CLOSE_TEXT_COLOR:'#FFFFFF',
    BTN_CLOSE_HOVER_BORDER_COLOR:"#CECECE",
    BTN_CLOSE_HOVER_TEXT_COLOR:'#F5BD41',

    BTN_RATING_BACKGROUND_COLOR: "#10367C",
    BTN_RATING_BACKGROUND_HOVER_COLOR: "#10467C",
    BTN_RATING_TEXT_COLOR:"#FFFFFF",


    BTN_TOP_BACKGROUND_COLOR:'#3077C6',
    BTN_TOP_BORDER_COLOR:"#3077C6",
    BTN_TOP_TEXT_COLOR:'#FFFFFF',
    BTN_TOP_HOVER_BACKGROUND_COLOR:'#FFFFFF',
    BTN_TOP_HOVER_BORDER_COLOR:"#3077C6",
    BTN_TOP_HOVER_TEXT_COLOR:'#3077C6',

}